spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dahanitdev.iptime.org:4001/dev2_study1
    username: root
    password: shw


  session:
    store-type: jdbc

  jpa: #JPA 설정
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect
      format_sql: true
      use_sql_comments: true
    show-sql: true
    generate-ddl: true



  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    order: 0

  h2:
    console:
      enabled: true


server:
  port: 8081
  error:
    include-exception: true
    include-stacktrace: always

log4jdbc: #log4jdbc 설정
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  dump:
    sql:
      maxlinelength: 0

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


